// Defined here rather than generated by Prisma because SQLite has no native
// enum type — the `status`/`priority` columns are plain strings, and these
// are the single source of truth for which values are valid.
export enum TaskStatus {
  pending = 'pending',
  in_progress = 'in_progress',
  completed = 'completed',
}

export enum TaskPriority {
  low = 'low',
  medium = 'medium',
  high = 'high',
}
